const constans = {
    NUMBER_SHOWED_MOVIES_PAGEWIDTH_1280: 12,
    NUMBER_ADDEDD_MOVIES_PAGEWIDTH_1280: 3,
    NUMBER_SHOWED_MOVIES_PAGEWIDTH_768: 8,
    NUMBER_ADDEDD_MOVIES_PAGEWIDTH_768: 2,
    NUMBER_SHOWED_MOVIES_PAGEWIDTH_480: 5,
    NUMBER_ADDEDD_MOVIES_PAGEWIDTH_480: 2,
    SHORT_MOVIE_DURATION: 40
}

export default constans
